project_id = "ytlynoknnvgpdkqsrfnl"

[functions.trial-notifications]
verify_jwt = false

[functions.nowpayments-currencies]
verify_jwt = true

[functions.nowpayments-create-payment]
verify_jwt = true

[functions.nowpayments-check-payment]
verify_jwt = true

[functions.telegram-signal-post]
verify_jwt = true

[functions.fetch-forex-news]
verify_jwt = false

[functions.fetch-live-prices]
verify_jwt = false

[functions.calculate-daily-stats]
verify_jwt = false

[functions.auto-generate-signals]
verify_jwt = false

[functions.auto-generate-ideas]
verify_jwt = false

[functions.mt5-demo-trade]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = false
